
QUOTER = ../util/quoter.exe
INCLUDER = ../util/includer.perl
BASE64 = base64
BASE64OPTIONS = -w 0
#BASE64OPTIONS = 

all : icon-empty.txt icon-I.txt icon-controlbit.txt icon-anticontrolbit.txt icon-H.txt icon-X.txt icon-Y.txt  icon-Z.txt icon-SX.txt icon-SY.txt icon-SZ.txt icon-SSX.txt icon-SSY.txt icon-SSZ.txt icon-invSX.txt icon-invSY.txt icon-invSZ.txt icon-invSSX.txt icon-invSSY.txt icon-invSSZ.txt icon-XE.txt icon-YE.txt icon-ZE.txt icon-RX.txt icon-RY.txt icon-RZ.txt icon-GP.txt icon-Ph.txt icon-ZG.txt icon-YG.txt icon-HG.txt icon-SWAP.txt

clean :
	rm icon-*.txt

# $@ is the target
# $^ is the prereqs

icon-empty.txt : icon-empty.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-I.txt : icon-I.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-controlbit.txt : icon-controlbit.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-anticontrolbit.txt : icon-anticontrolbit.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-H.txt : icon-H.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-X.txt : icon-X.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-Y.txt : icon-Y.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-Z.txt : icon-Z.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-SX.txt : icon-SX.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-SY.txt : icon-SY.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-SZ.txt : icon-SZ.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-SSX.txt : icon-SSX.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-SSY.txt : icon-SSY.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-SSZ.txt : icon-SSZ.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-invSX.txt : icon-invSX.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-invSY.txt : icon-invSY.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-invSZ.txt : icon-invSZ.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-invSSX.txt : icon-invSSX.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-invSSY.txt : icon-invSSY.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-invSSZ.txt : icon-invSSZ.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-XE.txt : icon-XE.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-YE.txt : icon-YE.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-ZE.txt : icon-ZE.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-RX.txt : icon-RX.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-RY.txt : icon-RY.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-RZ.txt : icon-RZ.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-GP.txt : icon-GP.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-Ph.txt : icon-Ph.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-SWAP.txt : icon-SWAP.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-ZG.txt : icon-ZG.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-YG.txt : icon-YG.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@

icon-HG.txt : icon-HG.png
	cat $^ | $(BASE64) $(BASE64OPTIONS) | $(QUOTER) > $@





